### ISSUE TITLE
Failed to run lmctl resourcedriver add

### ISSUE THREAD

**Issue by aviweit** [accanto-systems/kubernetes-driver#1]
Hi,

When I run:

`lmctl resourcedriver add --type kubernetes --url https://kubedriver:8294 --certificate kubedriver-tls.pem dev-env`

per instructions provided at https://github.com/accanto-systems/kubernetes-driver/blob/master/docs/install.md, I got

`Error: No such command 'resourcedriver'.`

However, when re-executing, changing resourcedriver to lifecycledriver i.e. `lmctl lifecycledriver add --type kubernetes --url https://kubedriver:8294 --certificate kubedriver-tls.pem dev-env`
then it worked.

My lmctl version is: 2.4.1

Thanks.

**Comment by dvaccarosenna** [comment]
Lmctl version 2.5.0+ is required. We will update the docs to make this clearer and close this issue.

**Comment by dvaccarosenna** [comment]
Fixed on master.
