### ISSUE TITLE
"Created on Other Transitions" section

### ISSUE THREAD

**Issue by aviweit** [accanto-systems/kubernetes-driver#7]
At section "Created on Other Transitions": https://github.com/accanto-systems/kubernetes-driver/blob/master/docs/user-guide/building-a-resource.md#created-on-other-transitions

Should the compose, in the example, be set to `Create` ? Because, to my understanding, for `Install`, it already implies that the cleanup is done on behalf of `Uninstall`.

```
cleanupOn: Uninstall
compose:
  - name: Create
...
```

Thanks.

**Comment by dvaccarosenna** [comment]
Yes the `Uninstall` covers `Install`. The example is more to show that there is a global cleanup, which defaults to `Delete` but can be another transition. It may be clearer to show the example using a few transitions, including maybe `Install` and `Start`. We didn't use `Create` as it doesn't make sense to have a `Create` then globally cleanup on `Uninstall`.

**Comment by aviweit** [comment]
I see. Thanks.
